dependencies:
  runtime:
    - java:8.202.08
    - maven:3.3.3
  build:
    - java:8.202.08
    - maven:3.3.3

build_targets:
  - name: default
    commands:
      - bash sleepy.sh
      - mvn package 

  - name: test
    commands:
      - mvn package

  - name: container_build
    container:
      image: maven:3.3.3
      workdir: /code
    commands:
      - mvn package

  - name: accelerated
    tags:
      channel: experimental
    build_after:
      - default

  - name: release
    build_after:
      - default
    commands:
      - echo RELEASE

ci:
  builds:
  - name: master_or_pr
    build_target: default
    report_status: true
    when: branch is 'master' OR action is 'pull_request'

  - name: release
    build_target: release
    when: tagged is true
 
