dependencies:
  runtime:
    - java:8.202.08
    - maven:3.3.3
  build:
    - java:8.202.08
    - maven:3.3.3
build:
  commands:
    - sleep 30
    - sh -c 'echo "${YB_GIT_COMMIT}"'
    - sh -c 'echo "${YB_GIT_BRANCH}"'
    - sh -c 'echo "${SAMWISE}"'
    - mvn package
exec:
  commands:
    - java -jar target/my-app-1.0-SNAPSHOT.jar
