dependencies:
  runtime:
    - java:8.202.08
    - maven:3.3.3
  build:
    - java:8.202.08
    - maven:3.3.3

# Build targets
build_targets:
  - name: default
    host_only: true
    container:
      image: yourbase/yb_ubuntu:18.04
    commands:
      - mvn package 

  - name: test
    commands:
      - mvn package

  - name: container_build
    container:
      image: yourbase/yb_ubuntu:18.04
      workdir: /code
    commands:
      - mvn package

  - name: accelerated
    tags:
      channel: experimental
    build_after:
      - default

  - name: release
    build_after:
      - default
    commands:
      - echo KRAKEN

# Only build when the override is forced.
ci:
  builds:
  - name: master_or_pr
    build_target: default
    report_status: true
    when: branch is 'master' OR action is 'pull_request'
