dependencies:
  runtime:
    - java:8.202.08
    - maven:3.3.3
  build:
    - java:8.202.08
    - maven:3.3.3
build:
  commands:
    - sh env.sh
    - mvn package
exec:
  commands:
    - java -jar target/my-app-1.0-SNAPSHOT.jar
