dependencies:
  runtime:
    - java:8.202.08
    - maven:3.3.3
  build:
    - java:8.202.08
    - maven:3.3.3

build_targets:
  - name: default
    tags:
      channel: experimental
    commands:
      - mvn package 

  - name: test
    tags:
      channel: experimental
    commands:
      - mvn package

  - name: pullrequest
    tags:
      channel: experimental
    commands:
      - echo "PULL REQUEST BUILD"
      - mvn package

  - name: container_build
    container:
      image: maven:3.3.3
      workdir: /code
    commands:
      - mvn package

  - name: accelerated
    tags:
      channel: experimental
    build_after:
      - default

  - name: release
    build_after:
      - default
    commands:
      - echo RELEASE

ci:
  builds:
  - name: accelerated
    build_target: accelerated 

  - name: master_builds
    build_target: default
    report_status: false
    when: branch is 'master' AND action is not 'pull_request'

  - name: pull_request_builds
    build_target: test
    when: branch is 'master' AND action is 'pull_request'
   
  - name: master_or_pr
    build_target: default
    report_status: true
    when: branch is 'master' OR action is 'pull_request'
   
  - name: pull request from any branch 
    build_target: pullrequest
    when: action is 'pull_request'

  - name: release
    build_target: release
    when: tagged is true
 
