   
dependencies:
  runtime:
    - java:8.202.08
    - maven:3.3.3
  build:
    - java:8.202.08
    - maven:3.3.3

build_targets:
  - name: test
    commands:
      - bash sleepy.sh
      - mvn package

  - name: android
    tags:
      os: linux
    build_after:
      - test
    commands:
      - echo "ANNNNNNDROIIIIIID"

  - name: ios
    tags:
      os: darwin
    build_after:
      - test
    commands:
      - echo "EEYYYYYEEEPHOOOONEEE"

ci:
  builds:
  - name: test_build
    build_target: test
    report_status: false
    when: branch is 'master' AND action is not 'pull_request'

  - name: quick_test
    build_target: test
    when: branch is 'master' AND action is 'pull_request'

  - name: release
    build_target: android
    when: tagged is true AND branch is 'master'
 
